name: Build

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Prepare build
        run: go install fyne.io/fyne/v2/cmd/fyne@latest && go install github.com/fyne-io/fyne-cross@latest

      - name: Build for Windows
        run: fyne-cross windows -icon Icon.png -arch=* -app-id com.virusrpi.flightcontrol

      - name: Build for Android
        run: fyne-cross android -icon Icon.png -arch=* -app-id com.virusrpi.flightcontrol

      - name: Build for Linux
        run: fyne-cross linux -icon Icon.png -arch=* -app-id com.virusrpi.flightcontrol

      - name: Save Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: ./fyne-cross/dist/*